export const START_GOOGLE_LOADING = "START_GOOGLE_LOADING";
export const START_NOTION_LOADING = "START_NOTION_LOADING";
export const GOOGLE_AUTH_DONE = "GOOGLE_AUTH_DONE";
export const NOTION_AUTH_DONE = "NOTION_AUTH_DONE";
